//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GossipDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostTemperory
    {
        public int PostID { get; set; }
        public string Subject { get; set; }
        public string Subject1 { get; set; }
        public string Subject2 { get; set; }
        public string ContentPost { get; set; }
        public string ContentPost1 { get; set; }
        public string ContentPost2 { get; set; }
        public string QuotedFrom { get; set; }
        public string Url { get; set; }
        public string UrlMP3 { get; set; }
        public string UrlVideo { get; set; }
        public Nullable<int> Views { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public Nullable<int> LikePost { get; set; }
        public Nullable<int> DislikePost { get; set; }
        public Nullable<int> PublishCount { get; set; }
        public string BackgroundColor { get; set; }
        public Nullable<int> ModifyUserID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsCreatedPost { get; set; }
    }
}
