//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GossipDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostCategory
    {
        public int PostCategoryID { get; set; }
        public Nullable<int> PostID_fk { get; set; }
        public Nullable<int> CategoryID_fk { get; set; }
    }
}
