//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GossipDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PubBase
    {
        public int PubBaseID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string NameFa { get; set; }
        public string NameEn { get; set; }
        public string GroupBase { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> ModifyUserID_fk { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
